DROP DATABASE IF EXISTS CASTUDTY_MODULE3;
CREATE DATABASE IF NOT EXISTS CASTUDTY_MODULE3;
USE CASTUDTY_MODULE3;

-- TABLE VI_TRI--  
CREATE TABLE VI_TRI (
    MA_VI_TRI INT PRIMARY KEY AUTO_INCREMENT,
    TEN_VI_TRI VARCHAR(45) NULL
);

-- TABLE TRINH_DO--
CREATE TABLE TRINH_DO (
    MA_TRINH_DO INT PRIMARY KEY AUTO_INCREMENT,
    TEN_TRINH_DO VARCHAR(45) NULL
);

-- TABLE BO_PHAN-- 
CREATE TABLE BO_PHAN (
    MA_BO_PHAN INT PRIMARY KEY AUTO_INCREMENT,
    TEN_BO_PHAN VARCHAR(45) NULL
);

-- TABLE NHAN_VIEN-- 
CREATE TABLE NHAN_VIEN (
    MA_NHAN_VIEN INT PRIMARY KEY AUTO_INCREMENT,
    HO_TEN VARCHAR(45) NOT NULL,
    NGAY_SINH DATE NOT NULL,
    SO_CMND VARCHAR(45) NOT NULL UNIQUE,
    LUONG DOUBLE,
    SO_DIEN_THOAI VARCHAR(45) NOT NULL UNIQUE,
    EMAIL VARCHAR(45) UNIQUE,
    DIA_CHI VARCHAR(45) NOT NULL UNIQUE,
    MA_VI_TRI INT NOT NULL,
    MA_TRINH_DO INT NOT NULL,
    MA_BO_PHAN INT NOT NULL,
    CONSTRAINT FK_VI_TRI FOREIGN KEY (MA_VI_TRI)
        REFERENCES VI_TRI (MA_VI_TRI),
    CONSTRAINT FK_TRINH_DO FOREIGN KEY (MA_TRINH_DO)
        REFERENCES TRINH_DO (MA_TRINH_DO),
    CONSTRAINT FK_BO_PHAN FOREIGN KEY (MA_BO_PHAN)
        REFERENCES BO_PHAN (MA_BO_PHAN)
);

-- TABEL LOAI_KHACH--  
CREATE TABLE LOAI_KHACH (
    MA_LOAI_KHACH INT PRIMARY KEY AUTO_INCREMENT,
    TEN_LOAI_KHACH VARCHAR(45) NULL
);

-- TABLE KHACH_HANG--  
CREATE TABLE KHACH_HANG (
    MA_KHACH_HANG INT PRIMARY KEY AUTO_INCREMENT,
    MA_LOAI_KHACH INT NOT NULL,
    HO_TEN VARCHAR(45) NOT NULL,
    NGAY_SINH DATE NOT NULL,
    GIOI_TINH BIT(1),
    SO_CMND VARCHAR(45) NOT NULL UNIQUE,
    SO_DIEN_THOAI VARCHAR(45) NOT NULL UNIQUE,
    EMAIL VARCHAR(45) UNIQUE,
    DIA_CHI VARCHAR(45) NOT NULL UNIQUE,
    CONSTRAINT FK_LOAI_KHACH FOREIGN KEY (MA_LOAI_KHACH)
        REFERENCES LOAI_KHACH (MA_LOAI_KHACH)
);

-- TABLE LOAI_DICH_VU--  
CREATE TABLE LOAI_DICH_VU (
    MA_LOAI_DICH_VU INT PRIMARY KEY AUTO_INCREMENT,
    TEN_LOAI_DICH_VU VARCHAR(45) NULL
);

-- TABLE KIEU_THUE--  
CREATE TABLE KIEU_THUE (
    MA_KIEU_THUE INT PRIMARY KEY AUTO_INCREMENT,
    TEN_KIEU_THUE VARCHAR(45) NULL
);

-- TABLE DICH_VU--
CREATE TABLE DICH_VU (MA_DICH_VU INT PRIMARY KEY AUTO_INCREMENT,
TEN_DICH_VU VARCHAR(45) NOT NULL,
DIEN_TICH INT NOT NULL DEFAULT("0"),
CHI_PHI_THUE DOUBLE NOT NULL,
SO_NGUOI_TOI_DA INT NOT NULL,
MA_KIEU_THUE INT NOT NULL,
MA_LOAI_DICH_VU INT NOT NULL,
TIEU_CHUAN_PHONG VARCHAR(45) NOT NULL,
MO_TA_TIEN_NGHI_KHAC VARCHAR(45),
DIEN_TICH_HO_BOI DOUBLE DEFAULT("0"),
SO_TANG INT DEFAULT("0"),
DICH_VU_MIEN_PHI_DI_KEM TEXT,
CONSTRAINT FK_KIEU_THUE FOREIGN KEY (MA_KIEU_THUE) REFERENCES KIEU_THUE(MA_KIEU_THUE),
CONSTRAINT FK_LOAI_DICH_VU FOREIGN KEY (MA_LOAI_DICH_VU) REFERENCES LOAI_DICH_VU(MA_LOAI_DICH_VU));

-- TABLE HOP_DONG--  
CREATE TABLE HOP_DONG(
MA_HOP_DONG INT PRIMARY KEY AUTO_INCREMENT,
NGAY_LAM_HOP_DONG DATETIME NOT NULL,
NGAY_KET_THUC DATETIME NOT NULL,
TIEN_DAT_COC DOUBLE,
MA_NHAN_VIEN INT NOT NULL,
MA_KHACH_HANG INT NOT NULL,
MA_DICH_VU INT NOT NULL,
CONSTRAINT FK_NHAN_VIEN FOREIGN KEY (MA_NHAN_VIEN) REFERENCES NHAN_VIEN(MA_NHAN_VIEN),
CONSTRAINT FK_KHACH_HANG FOREIGN KEY (MA_KHACH_HANG) REFERENCES KHACH_HANG(MA_KHACH_HANG),
CONSTRAINT FK_DICH_VU FOREIGN KEY (MA_DICH_VU) REFERENCES DICH_VU(MA_DICH_VU));

-- TABLE DICH_VU_DI_KEM--   
CREATE TABLE DICH_VU_DI_KEM(
MA_DICH_VU_DI_KEM INT PRIMARY KEY AUTO_INCREMENT,
TEN_DICH_VU_DI_KEM VARCHAR(45) NOT NULL,
GIA DOUBLE,
DON_VI VARCHAR(10) DEFAULT("0"),
TRANG_THAI VARCHAR(45) DEFAULT("..."));

-- TABLE HOP_DONG_DI_KEM--  
CREATE TABLE HOP_DONG_CHI_TIET (
MA_HOP_DONG_CHI_TIET INT PRIMARY KEY AUTO_INCREMENT,
MA_HOP_DONG INT NOT NULL,
MA_DICH_VU_DI_KEM INT NOT NULL,
CONSTRAINT FK_DICH_VU_DI_KEM FOREIGN KEY (MA_DICH_VU_DI_KEM) REFERENCES DICH_VU_DI_KEM(MA_DICH_VU_DI_KEM),
CONSTRAINT FK_HOP_DONG FOREIGN KEY (MA_HOP_DONG) REFERENCES HOP_DONG(MA_HOP_DONG),
SO_LUONG INT DEFAULT("0"));
