USE CASTUDTY_MODULE3;
-- TASK 4 CÂU 2
-- HIỂN THỊ THÔNG TIN CỦA TẤT CẢ NHÂN VIÊN CÓ TRONG HỆ THỐNG CÓ TÊN BẮT ĐẦU LÀ MỘT TRONG CÁC KÝ TỰ “H”, “T” HOẶC “K” VÀ CÓ TỐI ĐA 15 KÍ TỰ.--  
SELECT 
    *
FROM
    NHAN_VIEN
WHERE
    (HO_TEN LIKE 'H%' OR HO_TEN LIKE 'K%'
        OR HO_TEN LIKE 'TÒNG%')
        AND CHAR_LENGTH(HO_TEN) < 16;
        
        
#=====TASK 4 CÂU 2        
#  HIỂN THỊ THÔNG TINKHÁCH HÀNG CÓ ĐỘ TUỔI TỪ 18 ĐẾN 50 TUỔI VÀ CÓ ĐỊA CHỈ Ở “ĐÀ NẴNG” HOẶC “QUẢNG TRỊ”.
SELECT * FROM KHACH_HANG
-- WHERE 18 <= DATEDIFF(CURDATE(),NGAY_SINH)/365.25 AND DATEDIFF(CURDATE(),NGAY_SINH)/365.25 <=50 
-- AND DIA_CHI LIKE "%ĐÀ NẴNG%" OR DIA_CHI LIKE "%QUẢNG TRỊ%";
WHERE TIMESTAMPDIFF(YEAR,NGAY_SINH,NOW()) >18 AND TIMESTAMPDIFF(YEAR,NGAY_SINH,NOW()) <50 AND DIA_CHI REGEXP('(QUẢNG TRỊ|ĐÀ NẴNG)');


-- TASK 4 CÂU 4--  
-- ĐẾM XEM TƯƠNG ỨNG VỚI MỖI KHÁCH HÀNG ĐÃ TỪNG ĐẶT PHÒNG BAO NHIÊU LẦN.
-- KẾT QUẢ HIỂN THỊ ĐƯỢC SẮP XẾP TĂNG DẦN THEO SỐ LẦN ĐẶT PHÒNG CỦA KHÁCH HÀNG. 
-- CHỈ ĐẾM NHỮNG KHÁCH HÀNG NÀO CÓ TÊN LOẠI KHÁCH HÀNG LÀ “DIAMOND”
SELECT 
    KHACH_HANG.HO_TEN,
    KHACH_HANG.MA_KHACH_HANG,
    COUNT(KHACH_HANG.MA_KHACH_HANG) AS SO_LAN_DAT_PHONG
FROM
    KHACH_HANG
        JOIN
    HOP_DONG ON KHACH_HANG.MA_KHACH_HANG = HOP_DONG.MA_KHACH_HANG
WHERE
    KHACH_HANG.MA_LOAI_KHACH = 1
GROUP BY (KHACH_HANG.MA_KHACH_HANG)
ORDER BY SO_LAN_DAT_PHONG;

-- TASK 4 CÂU 5 -- 
-- HIỂN THỊ MA_KHACH_HANG, HO_TEN, TEN_LOAI_KHACH, MA_HOP_DONG, TEN_DICH_VU, NGAY_LAM_HOP_DONG,
-- NGAY_KET_THUC, TONG_TIEN (VỚI TỔNG TIỀN ĐƯỢC TÍNH THEO CÔNG THỨC NHƯ SAU:
--  CHI PHÍ THUÊ + SỐ LƯỢNG * GIÁ, VỚI SỐ LƯỢNG VÀ GIÁ LÀ TỪ BẢNG DICH_VU_DI_KEM, HOP_DONG_CHI_TIET) CHO TẤT CẢ CÁC KHÁCH HÀNG ĐÃ TỪNG ĐẶT PHÒNG.
-- (NHỮNG KHÁCH HÀNG NÀO CHƯA TỪNG ĐẶT PHÒNG CŨNG PHẢI HIỂN THỊ RA).
SELECT 
    KHACH_HANG.MA_KHACH_HANG,
    KHACH_HANG.HO_TEN,
    LOAI_KHACH.TEN_LOAI_KHACH,
    HOP_DONG.MA_HOP_DONG,
    HOP_DONG.NGAY_LAM_HOP_DONG,
    HOP_DONG.NGAY_KET_THUC,
    DICH_VU.TEN_DICH_VU,
    DICH_VU_DI_KEM.TEN_DICH_VU_DI_KEM,
    DICH_VU_DI_KEM.GIA,
    IFNULL(DICH_VU.CHI_PHI_THUE, 0) + SUM(IFNULL(DICH_VU_DI_KEM.GIA, 0) * IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0)) AS TONG_TIEN
FROM
    KHACH_HANG
        LEFT JOIN
    LOAI_KHACH ON KHACH_HANG.MA_LOAI_KHACH = LOAI_KHACH.MA_LOAI_KHACH
        LEFT JOIN
    HOP_DONG ON KHACH_HANG.MA_KHACH_HANG = HOP_DONG.MA_KHACH_HANG
        LEFT JOIN
    DICH_VU ON HOP_DONG.MA_DICH_VU = DICH_VU.MA_DICH_VU
        LEFT JOIN
    HOP_DONG_CHI_TIET ON HOP_DONG.MA_HOP_DONG = HOP_DONG_CHI_TIET.MA_HOP_DONG
        LEFT JOIN
    DICH_VU_DI_KEM ON HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM = DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM
GROUP BY MA_HOP_DONG , MA_KHACH_HANG;
    
-- TASK 5 CÂU 6 -- 
--  HIỂN THỊ MA_DICH_VU, TEN_DICH_VU, DIEN_TICH, CHI_PHI_THUE,
-- TEN_LOAI_DICH_VU CỦA TẤT CẢ CÁC LOẠI DỊCH VỤ CHƯA TỪNG ĐƯỢC KHÁCH HÀNG THỰC HIỆN ĐẶT TỪ QUÝ 1 CỦA NĂM 2021 (QUÝ 1 LÀ THÁNG 1, 2, 3).
SELECT 
    DICH_VU.MA_DICH_VU,
    DICH_VU.TEN_DICH_VU,
    DICH_VU.DIEN_TICH,
    DICH_VU.CHI_PHI_THUE,
    LOAI_DICH_VU.TEN_LOAI_DICH_VU,
    HOP_DONG.NGAY_LAM_HOP_DONG
FROM
    DICH_VU
        LEFT JOIN
    LOAI_DICH_VU ON DICH_VU.MA_LOAI_DICH_VU = LOAI_DICH_VU.MA_LOAI_DICH_VU
        JOIN
    HOP_DONG ON DICH_VU.MA_DICH_VU = HOP_DONG.MA_DICH_VU
WHERE
    DICH_VU.MA_DICH_VU NOT IN (SELECT 
            MA_DICH_VU
        FROM
            HOP_DONG
        WHERE
            MONTH(NGAY_LAM_HOP_DONG) IN (1 , 2, 3)
                AND YEAR(NGAY_LAM_HOP_DONG) = '2021')
GROUP BY DICH_VU.MA_DICH_VU
ORDER BY TEN_DICH_VU DESC;
       
-- TASK 5 CÂU7--
-- HIỂN THỊ THÔNG TIN MA_DICH_VU, TEN_DICH_VU, DIEN_TICH, SO_NGUOI_TOI_DA, CHI_PHI_THUE, TEN_LOAI_DICH_VU
-- CỦA TẤT CẢ CÁC LOẠI DỊCH VỤ ĐÃ TỪNG ĐƯỢC KHÁCH HÀNG ĐẶT PHÒNG TRONG NĂM 2020 NHƯNG CHƯA TỪNG ĐƯỢC KHÁCH HÀNG ĐẶT PHÒNG TRONG NĂM 2021.
SELECT 
    DICH_VU.MA_DICH_VU,
    DICH_VU.TEN_DICH_VU,
    DICH_VU.DIEN_TICH,
    DICH_VU.CHI_PHI_THUE,
    LOAI_DICH_VU.TEN_LOAI_DICH_VU,
    HOP_DONG.NGAY_LAM_HOP_DONG,
    DICH_VU.SO_NGUOI_TOI_DA
FROM
    DICH_VU
        LEFT JOIN
    LOAI_DICH_VU ON DICH_VU.MA_LOAI_DICH_VU = LOAI_DICH_VU.MA_LOAI_DICH_VU
        JOIN
    HOP_DONG ON DICH_VU.MA_DICH_VU = HOP_DONG.MA_DICH_VU
WHERE
    YEAR(HOP_DONG.NGAY_LAM_HOP_DONG) = '2020'
        AND DICH_VU.MA_DICH_VU NOT IN (SELECT 
            MA_DICH_VU
        FROM
            HOP_DONG
        WHERE
            YEAR(NGAY_LAM_HOP_DONG) = '2021')
GROUP BY DICH_VU.MA_DICH_VU
ORDER BY TEN_DICH_VU DESC;

-- TASK 5 CÂU 8 --
-- HIỂN THỊ THÔNG TIN HO_TEN KHÁCH HÀNG CÓ TRONG HỆ THỐNG, VỚI YÊU CẦU HO_TEN KHÔNG TRÙNG NHAU. (3 CÁCH)
SELECT DISTINCT  KHACH_HANG.HO_TEN FROM KHACH_HANG;
SELECT KHACH_HANG.HO_TEN FROM KHACH_HANG
GROUP BY KHACH_HANG.HO_TEN;
SELECT KHACH_HANG.HO_TEN FROM KHACH_HANG
UNION
SELECT KHACH_HANG.HO_TEN FROM KHACH_HANG;

-- TASK 5 CÂU 9 --
-- THỰC HIỆN THỐNG KÊ DOANH THU THEO THÁNG, 
-- NGHĨA LÀ TƯƠNG ỨNG VỚI MỖI THÁNG TRONG NĂM 2021 THÌ SẼ CÓ BAO NHIÊU KHÁCH HÀNG THỰC HIỆN ĐẶT PHÒNG. 
SELECT 
    MONTH(NGAY_LAM_HOP_DONG) AS `MONTH`,
    COUNT(MONTH(NGAY_LAM_HOP_DONG)) AS SO_LUONG_KHACH_HANG
FROM
    HOP_DONG
WHERE
    YEAR(NGAY_LAM_HOP_DONG) = '2021'
GROUP BY `MONTH`
ORDER BY `MONTH`;

-- TASK 5 CÂU 10 --
-- HIỂN THỊ THÔNG TIN TƯƠNG ỨNG VỚI TỪNG HỢP ĐỒNG THÌ ĐÃ SỬ DỤNG BAO NHIÊU DỊCH VỤ ĐI KÈM.
-- KẾT QUẢ HIỂN THỊ BAO GỒM MA_HOP_DONG, NGAY_LAM_HOP_DONG, NGAY_KET_THUC, TIEN_DAT_COC,
-- SO_LUONG_DICH_VU_DI_KEM (ĐƯỢC TÍNH DỰA TRÊN VIỆC SUM SO_LUONG Ở HOP_DONG_CHI_TIET).
SELECT 
    HOP_DONG.MA_HOP_DONG,
    HOP_DONG.NGAY_LAM_HOP_DONG,
    HOP_DONG.NGAY_KET_THUC,
    HOP_DONG.TIEN_DAT_COC,
    SUM(IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0)) AS SO_LUONG_DICH_VU_DI_KEM
FROM
    HOP_DONG
        LEFT JOIN
    HOP_DONG_CHI_TIET ON HOP_DONG.MA_HOP_DONG = HOP_DONG_CHI_TIET.MA_HOP_DONG
        LEFT JOIN
    DICH_VU_DI_KEM ON HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM = DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM
GROUP BY HOP_DONG.MA_HOP_DONG;

-- TASK 6 CÂU 11 --
-- HIỂN THỊ THÔNG TIN CÁC DỊCH VỤ ĐI KÈM ĐÃ ĐƯỢC SỬ DỤNG BỞI NHỮNG KHÁCH HÀNG CÓ TEN_LOAI_KHACH LÀ “DIAMOND” 
-- VÀ CÓ DIA_CHI Ở “VINH” HOẶC “QUẢNG NGÃI”.
SELECT 
    DICH_VU_DI_KEM.*,
    KHACH_HANG.HO_TEN,
    LOAI_KHACH.TEN_LOAI_KHACH,
    KHACH_HANG.DIA_CHI
FROM
    DICH_VU_DI_KEM
        JOIN
    HOP_DONG_CHI_TIET ON DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM = HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM
        JOIN
    HOP_DONG ON HOP_DONG.MA_HOP_DONG = HOP_DONG_CHI_TIET.MA_HOP_DONG
        JOIN
    KHACH_HANG ON KHACH_HANG.MA_KHACH_HANG = HOP_DONG.MA_KHACH_HANG
        JOIN
    LOAI_KHACH ON LOAI_KHACH.MA_LOAI_KHACH = KHACH_HANG.MA_LOAI_KHACH
WHERE
    KHACH_HANG.MA_LOAI_KHACH = 1
        AND KHACH_HANG.DIA_CHI REGEXP ('(VINH|QUẢNG NGÃI)');

-- TASK 6 CÂU 12 --
-- HIỂN THỊ THÔNG TIN MA_HOP_DONG, HO_TEN (NHÂN VIÊN), HO_TEN (KHÁCH HÀNG), SO_DIEN_THOAI (KHÁCH HÀNG), 
-- TEN_DICH_VU, SO_LUONG_DICH_VU_DI_KEM (ĐƯỢC TÍNH DỰA TRÊN VIỆC SUM SO_LUONG Ở HOP_DONG_CHI_TIET),
-- TIEN_DAT_COC CỦA TẤT CẢ CÁC DỊCH VỤ ĐÃ TỪNG ĐƯỢC KHÁCH HÀNG ĐẶT VÀO 3 THÁNG CUỐI NĂM 2020 NHƯNG CHƯA TỪNG ĐƯỢC KHÁCH HÀNG ĐẶT VÀO 6 THÁNG ĐẦU NĂM 2021.
SELECT 
    HOP_DONG.MA_HOP_DONG,
    KHACH_HANG.HO_TEN,
    NHAN_VIEN.HO_TEN,
    KHACH_HANG.SO_DIEN_THOAI,
    DICH_VU.TEN_DICH_VU,
    HOP_DONG.TIEN_DAT_COC,
    DICH_VU_DI_KEM.TEN_DICH_VU_DI_KEM,
    HOP_DONG.NGAY_LAM_HOP_DONG,
    SUM(IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0)) AS SO_LUONG_DICH_VU_DI_KEM
FROM
    DICH_VU
        JOIN
    HOP_DONG ON DICH_VU.MA_DICH_VU = HOP_DONG.MA_DICH_VU
        LEFT JOIN
    KHACH_HANG ON KHACH_HANG.MA_KHACH_HANG = HOP_DONG.MA_KHACH_HANG
        LEFT JOIN
    NHAN_VIEN ON HOP_DONG.MA_NHAN_VIEN = NHAN_VIEN.MA_NHAN_VIEN
        LEFT JOIN
    HOP_DONG_CHI_TIET ON HOP_DONG_CHI_TIET.MA_HOP_DONG = HOP_DONG.MA_HOP_DONG
        LEFT JOIN
    DICH_VU_DI_KEM ON HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM = DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM
WHERE
    YEAR(HOP_DONG.NGAY_LAM_HOP_DONG) = '2020'
        AND MONTH(HOP_DONG.NGAY_LAM_HOP_DONG) IN (10 , 11, 12)
        AND DICH_VU.MA_DICH_VU NOT IN (SELECT 
            MA_DICH_VU
        FROM
            HOP_DONG
        WHERE
            MONTH(NGAY_LAM_HOP_DONG) IN (1 , 2, 3, 4, 5, 6)
                AND YEAR(NGAY_LAM_HOP_DONG) = '2021')
GROUP BY MA_HOP_DONG;

-- TASK 6 CÂU 13 --
-- HIỂN THỊ THÔNG TIN CÁC DỊCH VỤ ĐI KÈM ĐƯỢC SỬ DỤNG NHIỀU NHẤT BỞI CÁC KHÁCH HÀNG ĐÃ ĐẶT PHÒNG. (LƯU Ý LÀ CÓ THỂ CÓ NHIỀU DỊCH VỤ CÓ SỐ LẦN SỬ DỤNG NHIỀU NHƯ NHAU).
SELECT 
    DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM,
    HOP_DONG_CHI_TIET.MA_HOP_DONG_CHI_TIET,
    DICH_VU_DI_KEM.TEN_DICH_VU_DI_KEM,
    SUM(IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0)) AS SO_LUONG_DICH_VU_DI_KEM
FROM
    HOP_DONG_CHI_TIET
        JOIN
    DICH_VU_DI_KEM ON HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM = DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM
GROUP BY DICH_VU_DI_KEM.TEN_DICH_VU_DI_KEM
HAVING SUM(IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0)) >= ALL (SELECT 
        SUM(IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0))
    FROM
        HOP_DONG_CHI_TIET
    GROUP BY HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM);
  
  -- TASK 6 CÂU 14 --
#HIỂN THỊ THÔNG TIN TẤT CẢ CÁC DỊCH VỤ ĐI KÈM CHỈ MỚI ĐƯỢC SỬ DỤNG MỘT LẦN DUY NHẤT.
#THÔNG TIN HIỂN THỊ BAO GỒM MA_HOP_DONG, TEN_LOAI_DICH_VU, TEN_DICH_VU_DI_KEM, SO_LAN_SU_DUNG (ĐƯỢC TÍNH DỰA TRÊN VIỆC COUNT CÁC MA_DICH_VU_DI_KEM).
SELECT 
    DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM,
    DICH_VU_DI_KEM.TEN_DICH_VU_DI_KEM,
    HOP_DONG_CHI_TIET.MA_HOP_DONG,
    LOAI_DICH_VU.TEN_LOAI_DICH_VU,
    COUNT(HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM) AS SO_LAN_SU_DUNG
FROM
    DICH_VU
        JOIN
    LOAI_DICH_VU ON DICH_VU.MA_LOAI_DICH_VU = LOAI_DICH_VU.MA_LOAI_DICH_VU
        JOIN
    HOP_DONG ON DICH_VU.MA_DICH_VU = HOP_DONG.MA_DICH_VU
        JOIN
    HOP_DONG_CHI_TIET ON HOP_DONG.MA_HOP_DONG = HOP_DONG_CHI_TIET.MA_HOP_DONG
        JOIN
    DICH_VU_DI_KEM ON HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM = DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM
GROUP BY DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM
HAVING SO_LAN_SU_DUNG = 1;

  -- TASK 6 CÂU 15 --
  #HIỂN THI THÔNG TIN CỦA TẤT CẢ NHÂN VIÊN BAO GỒM MA_NHAN_VIEN, HO_TEN, TEN_TRINH_DO, TEN_BO_PHAN,
  #SO_DIEN_THOAI, DIA_CHI MỚI CHỈ LẬP ĐƯỢC TỐI ĐA 3 HỢP ĐỒNG TỪ NĂM 2020 ĐẾN 2021.
SELECT 
    NHAN_VIEN.MA_NHAN_VIEN,
    NHAN_VIEN.HO_TEN,
    TRINH_DO.TEN_TRINH_DO,
    BO_PHAN.TEN_BO_PHAN,
    NHAN_VIEN.SO_DIEN_THOAI,
    NHAN_VIEN.DIA_CHI
FROM
    NHAN_VIEN
        JOIN
    VI_TRI ON NHAN_VIEN.MA_VI_TRI = VI_TRI.MA_VI_TRI
        JOIN
    TRINH_DO ON NHAN_VIEN.MA_TRINH_DO = TRINH_DO.MA_TRINH_DO
        JOIN
    BO_PHAN ON NHAN_VIEN.MA_BO_PHAN = BO_PHAN.MA_BO_PHAN
        JOIN
    HOP_DONG ON NHAN_VIEN.MA_NHAN_VIEN = HOP_DONG.MA_NHAN_VIEN
WHERE
    YEAR(HOP_DONG.NGAY_LAM_HOP_DONG) IN (2020 , 2021)
GROUP BY HOP_DONG.MA_NHAN_VIEN
HAVING COUNT(HOP_DONG.MA_NHAN_VIEN) <= 3;

-- TASK 7 CÂU 16 --
#XÓA NHỮNG NHÂN VIÊN CHƯA TỪNG LẬP ĐƯỢC HỢP ĐỒNG NÀO TỪ NĂM 2019 ĐẾN NĂM 2021.	
SET SQL_SAFE_UPDATES = 0;
DELETE FROM NHAN_VIEN 
WHERE
    NHAN_VIEN.MA_NHAN_VIEN NOT IN (SELECT 
        *
    FROM
        (SELECT 
            NHAN_VIEN.MA_NHAN_VIEN
        FROM
            NHAN_VIEN
        LEFT JOIN HOP_DONG ON NHAN_VIEN.MA_NHAN_VIEN = HOP_DONG.MA_NHAN_VIEN
        
        WHERE
            HOP_DONG.NGAY_LAM_HOP_DONG BETWEEN '2019-01-01' AND '2021-12-31') AS X);
SELECT * FROM NHAN_VIEN;
SET SQL_SAFE_UPDATES = 1;

-- SET SQL_SAFE_UPDATES = 0;
-- DELETE FROM NHAN_VIEN
-- WHERE MA_NHAN_VIEN NOT IN (
-- SELECT HD.MA_NHAN_VIEN
-- FROM HOP_DONG HD
-- GROUP BY HD.MA_NHAN_VIEN
-- );
-- SET SQL_SAFE_UPDATES = 1;
-- SELECT * FROM NHAN_VIEN;

-- TASK 7 CÂU 17 --
# CẬP NHẬT THÔNG TIN NHỮNG KHÁCH HÀNG CÓ TEN_LOAI_KHACH TỪ PLATINUM LÊN DIAMOND,
# CHỈ CẬP NHẬT NHỮNG KHÁCH HÀNG ĐÃ TỪNG ĐẶT PHÒNG VỚI TỔNG TIỀN THANH TOÁN TRONG NĂM 2021 LÀ LỚN HƠN 10.000.000 VNĐ.
# TỔNG TIỀN THANH TOÁN = CHI PHÍ THUÊ + SỐ LƯỢNG * GIÁ

CREATE VIEW W_ABC AS
    (SELECT 
        MKH, HT, SUM(VIEW_TABLE.TONG_TIEN) AS TONG_CHI_PHI
    FROM
        (SELECT 
            KHACH_HANG.MA_KHACH_HANG MKH,
                KHACH_HANG.HO_TEN HT,
                IFNULL(DICH_VU.CHI_PHI_THUE, 0) + SUM(IFNULL(DICH_VU_DI_KEM.GIA, 0) * IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0)) AS TONG_TIEN
        FROM
            KHACH_HANG
        JOIN LOAI_KHACH ON KHACH_HANG.MA_LOAI_KHACH = LOAI_KHACH.MA_LOAI_KHACH
        JOIN HOP_DONG ON KHACH_HANG.MA_KHACH_HANG = HOP_DONG.MA_KHACH_HANG
        LEFT JOIN DICH_VU ON HOP_DONG.MA_DICH_VU = DICH_VU.MA_DICH_VU
        LEFT JOIN HOP_DONG_CHI_TIET ON HOP_DONG.MA_HOP_DONG = HOP_DONG_CHI_TIET.MA_HOP_DONG
        LEFT JOIN DICH_VU_DI_KEM ON HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM = DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM
        WHERE
            LOAI_KHACH.TEN_LOAI_KHACH REGEXP ('PLATINIUM')
                AND YEAR(HOP_DONG.NGAY_LAM_HOP_DONG) = 2021
        GROUP BY HOP_DONG.MA_HOP_DONG , KHACH_HANG.MA_LOAI_KHACH
        HAVING TONG_TIEN > 1000000) AS VIEW_TABLE
    GROUP BY MKH);
SET SQL_SAFE_UPDATES = 0;
UPDATE KHACH_HANG 
SET 
    KHACH_HANG.MA_LOAI_KHACH = 1
WHERE
    KHACH_HANG.MA_KHACH_HANG IN (SELECT 
            *
        FROM
            (SELECT MKH FROM W_ABC) AS W);
SELECT * FROM KHACH_HANG;
SET SQL_SAFE_UPDATES = 1;
SELECT MKH FROM W_ABC;

-- TASK 7 CÂU 18 --
# XÓA NHỮNG KHÁCH HÀNG CÓ HỢP ĐỒNG TRƯỚC NĂM 2021 (CHÚ Ý RÀNG BUỘC GIỮA CÁC BẢNG).
SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0; 
DELETE FROM KHACH_HANG 
WHERE
    KHACH_HANG.MA_KHACH_HANG IN (SELECT 
        *
    FROM
        (SELECT 
            KHACH_HANG.MA_KHACH_HANG
        FROM
            KHACH_HANG
        JOIN HOP_DONG ON KHACH_HANG.MA_KHACH_HANG = HOP_DONG.MA_KHACH_HANG
        WHERE
            YEAR(HOP_DONG.NGAY_LAM_HOP_DONG) <2021) AS U);
SELECT * FROM NHAN_VIEN;
SET SQL_SAFE_UPDATES = 1;

-- TASK 7 CÂU 19 --
#CẬP NHẬT GIÁ CHO CÁC DỊCH VỤ ĐI KÈM ĐƯỢC SỬ DỤNG TRÊN 10 LẦN TRONG NĂM 2020 LÊN GẤP ĐÔI.
SET SQL_SAFE_UPDATES = 0;
SELECT * FROM DICH_VU_DI_KEM;
UPDATE DICH_VU_DI_KEM 
SET 
    DICH_VU_DI_KEM.GIA = DICH_VU_DI_KEM.GIA * 2
WHERE
    DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM IN (SELECT 
            TB_VIEW.MA_DICH_VU_DI_KEM
        FROM
            (SELECT 
                HOP_DONG_CHI_TIET.MA_HOP_DONG,
				DICH_VU_DI_KEM.TEN_DICH_VU_DI_KEM,
				HOP_DONG_CHI_TIET.SO_LUONG,
				DICH_VU_DI_KEM.GIA,
				HOP_DONG.NGAY_LAM_HOP_DONG,
				DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM,
				SUM(IFNULL(HOP_DONG_CHI_TIET.SO_LUONG, 0)) AS TSL
            FROM
                DICH_VU_DI_KEM
            JOIN HOP_DONG_CHI_TIET ON DICH_VU_DI_KEM.MA_DICH_VU_DI_KEM = HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM
            JOIN HOP_DONG ON HOP_DONG_CHI_TIET.MA_HOP_DONG = HOP_DONG.MA_HOP_DONG
            WHERE
                YEAR(HOP_DONG.NGAY_LAM_HOP_DONG) = 2020
            GROUP BY HOP_DONG_CHI_TIET.MA_DICH_VU_DI_KEM
            HAVING TSL > 10) AS TB_VIEW);
SELECT 
    *
FROM
    DICH_VU_DI_KEM;
SET SQL_SAFE_UPDATES = 1;

-- TASK 8 CÂU 20 --
#HIỂN THỊ THÔNG TIN CỦA TẤT CẢ CÁC NHÂN VIÊN VÀ KHÁCH HÀNG CÓ TRONG HỆ THỐNG,
#THÔNG TIN HIỂN THỊ BAO GỒM ID (MA_NHAN_VIEN, MA_KHACH_HANG),
#HO_TEN, EMAIL, SO_DIEN_THOAI, NGAY_SINH, DIA_CHI.
SELECT NHAN_VIEN.HO_TEN,NHAN_VIEN.EMAIL,NHAN_VIEN.SO_DIEN_THOAI,NHAN_VIEN.NGAY_SINH,NHAN_VIEN.DIA_CHI FROM NHAN_VIEN 
UNION
SELECT KHACH_HANG.HO_TEN,KHACH_HANG.EMAIL,KHACH_HANG.SO_DIEN_THOAI,KHACH_HANG.NGAY_SINH,KHACH_HANG.DIA_CHI FROM KHACH_HANG;

-- TASK 8 CÂU 21 --
#TẠO KHUNG NHÌN CÓ TÊN LÀ V_NHAN_VIEN ĐỂ LẤY ĐƯỢC THÔNG TIN CỦA TẤT CẢ CÁC NHÂN VIÊN CÓ ĐỊA CHỈ LÀ “GIA LAI” 
#VÀ ĐÃ TỪNG LẬP HỢP ĐỒNG CHO MỘT HOẶC NHIỀU KHÁCH HÀNG BẤT KÌ VỚI NGÀY LẬP HỢP ĐỒNG LÀ “2020-11-19”.
CREATE VIEW V_NHAN_VIEN AS
    (SELECT 
        NHAN_VIEN.*, HOP_DONG.NGAY_LAM_HOP_DONG
    FROM
        NHAN_VIEN
            JOIN
        HOP_DONG ON NHAN_VIEN.MA_NHAN_VIEN = HOP_DONG.MA_NHAN_VIEN
    WHERE
        NHAN_VIEN.DIA_CHI REGEXP ('GIA LAI')
            AND HOP_DONG.NGAY_LAM_HOP_DONG = "2020-11-19");
         
-- TASK 8 CÂU 22 --
#THÔNG QUA KHUNG NHÌN V_NHAN_VIEN THỰC HIỆN CẬP NHẬT ĐỊA CHỈ THÀNH “VIỆT NAM” ĐỐI VỚI TẤT CẢ CÁC NHÂN VIÊN ĐƯỢC NHÌN THẤY BỞI KHUNG NHÌN NÀY.
SET SQL_SAFE_UPDATES = 0;
UPDATE NHAN_VIEN
SET NHAN_VIEN.DIA_CHI="VIỆT NAM"
WHERE NHAN_VIEN.MA_NHAN_VIEN IN (
SELECT * FROM (
SELECT MA_NHAN_VIEN FROM V_NHAN_VIEN) AS SET_DIA_CHI);
SET SQL_SAFE_UPDATES = 1;
SELECT * FROM NHAN_VIEN; 

-- TASK 8 CÂU 23 --
#TẠO STORED PROCEDURE SP_XOA_KHACH_HANG DÙNG ĐỂ XÓA THÔNG TIN CỦA MỘT KHÁCH HÀNG NÀO ĐÓ VỚI MA_KHACH_HANG ĐƯỢC TRUYỀN VÀO NHƯ LÀ 1 THAM SỐ CỦA SP_XOA_KHACH_HANG. 
SET FOREIGN_KEY_CHECKS = 0; 
DELIMITER //
CREATE PROCEDURE SP_XOA_KHACH_HANG(IN SP_MKH INT)
BEGIN
DELETE FROM KHACH_HANG WHERE KHACH_HANG.MA_KHACH_HANG = SP_MKH;
END //
DELIMITER ;
 CALL SP_XOA_KHACH_HANG(4);
 SET FOREIGN_KEY_CHECKS = 1; 

-- TASK 8 CÂU 24 --
#TẠO STORED PROCEDURE SP_THEM_MOI_HOP_DONG DÙNG ĐỂ THÊM MỚI VÀO BẢNG HOP_DONG
#VỚI YÊU CẦU SP_THEM_MOI_HOP_DONG PHẢI THỰC HIỆN KIỂM TRA TÍNH HỢP LỆ CỦA DỮ LIỆU BỔ SUNG,
#VỚI NGUYÊN TẮC KHÔNG ĐƯỢC TRÙNG KHÓA CHÍNH VÀ ĐẢM BẢO TOÀN VẸN THAM CHIẾU ĐẾN CÁC BẢNG LIÊN QUAN.
DELIMITER //
CREATE PROCEDURE SP_THEM_MOI_HOP_DONG(IN SP_NGAY_LAM_HOP_DONG DATETIME,
SP_NGAY_KET_THUC DATETIME,
SP_TIEN_DAT_COC DOUBLE,
SP_MA_NHAN_VIEN INT,
SP_MA_KHACH_HANG INT,
SP_MA_DICH_VU INT)
BEGIN
 INSERT INTO HOP_DONG(NGAY_LAM_HOP_DONG, NGAY_KET_THUC, TIEN_DAT_COC, MA_NHAN_VIEN, MA_KHACH_HANG, MA_DICH_VU) 
 VALUE (SP_NGAY_LAM_HOP_DONG,SP_NGAY_KET_THUC,SP_TIEN_DAT_COC,SP_MA_NHAN_VIEN,SP_MA_KHACH_HANG,SP_MA_DICH_VU);
END//
DELIMITER ;
CALL SP_THEM_MOI_HOP_DONG('2021-05-29','2021-06-11',0,7,9,1);
SELECT * FROM HOP_DONG;

#=======================TASK 8 CÂU 25=================================#
#TẠO TRIGGER CÓ TÊN TR_XOA_HOP_DONG KHI XÓA BẢN GHI TRONG BẢNG HOP_DONG 
#THÌ HIỂN THỊ TỔNG SỐ LƯỢNG BẢN GHI CÒN LẠI CÓ TRONG BẢNG HOP_DONG RA GIAO DIỆN CONSOLE CỦA DATABASE.
CREATE TABLE SO_LUONG_BAN_GHI(
SO_LUONG_BAN_GHI INT,
DELETE_DAY DATETIME DEFAULT NOW()); 
DELIMITER //
CREATE TRIGGER XOA_HOP_DONG
AFTER DELETE ON HOP_DONG
FOR EACH ROW
BEGIN
INSERT INTO SO_LUONG_BAN_GHI(SO_LUONG_BAN_GHI) 
VALUE((SELECT COUNT(*) FROM HOP_DONG));
END//
DELIMITER ;
SET SQL_SAFE_UPDATES = 0;
SET FOREIGN_KEY_CHECKS = 0; 
DELETE FROM HOP_DONG 
	WHERE HOP_DONG.MA_HOP_DONG = 1;
DELETE FROM HOP_DONG 
	WHERE HOP_DONG.MA_HOP_DONG = 6;
SELECT * FROM SO_LUONG_BAN_GHI;
DROP TRIGGER XOA_HOP_DONG;
#======================== TASK 8 CÂU 26=====================#
#==TẠO TRIGGER CÓ TÊN TR_CAP_NHAT_HOP_DONG KHI CẬP NHẬT NGÀY KẾT THÚC HỢP ĐỒNG, CẦN KIỂM TRA XEM THỜI GIAN CẬP NHẬT CÓ PHÙ HỢP HAY KHÔNG, 
#==VỚI QUY TẮC SAU: NGÀY KẾT THÚC HỢP ĐỒNG PHẢI LỚN HƠN NGÀY LÀM HỢP ĐỒNG ÍT NHẤT LÀ 2 NGÀY.
#==NẾU DỮ LIỆU HỢP LỆ THÌ CHO PHÉP CẬP NHẬT, NẾU DỮ LIỆU KHÔNG HỢP LỆ THÌ IN RA THÔNG BÁO “NGÀY KẾT THÚC HỢP ĐỒNG PHẢI LỚN HƠN NGÀY LÀM HỢP ĐỒNG ÍT NHẤT LÀ 2 NGÀY” TRÊN CONSOLE CỦA DATABASE.
DELIMITER //
CREATE TRIGGER TR_CAP_NHAT_HOP_DONG
BEFORE UPDATE ON HOP_DONG
FOR EACH ROW
BEGIN
DECLARE ERROR_MESSAGE VARCHAR(225);
IF DATEDIFF(NEW.NGAY_KET_THUC,OLD.NGAY_LAM_HOP_DONG) < 2 THEN
SET ERROR_MESSAGE="NGÀY KẾT THÚC HỢP ĐỒNG PHẢI LỚN HƠN NGÀY LÀM HỢP ĐỒNG ÍT NHẤT LÀ 2 NGÀY";
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = ERROR_MESSAGE;
END IF;
END//
DELIMITER ;
SET SQL_SAFE_UPDATES = 0;
UPDATE HOP_DONG
SET NGAY_KET_THUC ="20210325"
WHERE MA_HOP_DONG= 4;
UPDATE HOP_DONG
SET NGAY_KET_THUC ="20210325"
WHERE MA_HOP_DONG= 3;
DROP TRIGGER TR_CAP_NHAT_HOP_DONG;

#======================== TASK 8 CÂU 27=====================#
#====TẠO FUNCTION THỰC HIỆN YÊU CẦU SAU:====†
#== A/TẠO FUNCTION FUNC_DEM_DICH_VU: ĐẾM CÁC DỊCH VỤ ĐÃ ĐƯỢC SỬ DỤNG VỚI TỔNG TIỀN LÀ > 2.000.000 VNĐ.==†
DELIMITER //
CREATE FUNCTION FUNC_DEM_DICH_VU ()
RETURNS INT
DETERMINISTIC
BEGIN
DECLARE SO_LAN_SU_DUNG INT;
SET SO_LAN_SU_DUNG = (SELECT COUNT(*)
FROM(SELECT DV.TEN_DICH_VU, COUNT(TEN_DICH_VU),SUM(CHI_PHI_THUE) TONG_TIEN FROM DICH_VU DV JOIN HOP_DONG HD ON DV.MA_DICH_VU=HD.MA_DICH_VU
GROUP BY TEN_DICH_VU
HAVING TONG_TIEN>2000000) AS A);
RETURN SO_LAN_SU_DUNG;
END //
DELIMITER ;
SELECT  FUNC_DEM_DICH_VU();

#== B/TẠO FUNCTION FUNC_TINH_THOI_GIAN_HOP_DONG: TÍNH KHOẢNG THỜI GIAN DÀI NHẤT TÍNH TỪ LÚC BẮT ĐẦU LÀM HỢP ĐỒNG ĐẾN LÚC KẾT THÚC HỢP ĐỒNG
#== MÀ KHÁCH HÀNG ĐÃ THỰC HIỆN THUÊ DỊCH VỤ (LƯU Ý CHỈ XÉT CÁC KHOẢNG THỜI GIAN DỰA VÀO TỪNG LẦN LÀM HỢP ĐỒNG THUÊ DỊCH VỤ, KHÔNG XÉT TRÊN TOÀN BỘ CÁC LẦN LÀM HỢP ĐỒNG)
#== MÃ CỦA KHÁCH HÀNG ĐƯỢC TRUYỀN VÀO NHƯ LÀ 1 THAM SỐ CỦA FUNCTION NÀY.
DELIMITER //
CREATE FUNCTION FUNC_TINH_THOI_GIAN_HOP_DONG (F_MA_KHACH_HANG INT)
RETURNS INT
DETERMINISTIC
BEGIN
RETURN (SELECT MAX(DATEDIFF(NGAY_KET_THUC,NGAY_LAM_HOP_DONG)) AS THOI_GIAN_THUE_DAI_NHAT FROM HOP_DONG
WHERE MA_KHACH_HANG=F_MA_KHACH_HANG);
END//
DELIMITER ;
SELECT FUNC_TINH_THOI_GIAN_HOP_DONG(2);


#======================== TASK 8 CÂU 28=====================#
#====Tạo Stored Procedure sp_xoa_dich_vu_va_hd_room để tìm các dịch vụ được thuê bởi khách hàng với loại dịch vụ là “Room” ===
#====từ đầu năm 2015 đến hết năm 2019 để xóa thông tin của các dịch vụ đó ===
#===(tức là xóa các bảng ghi trong bảng dich_vu) và xóa những hop_dong sử dụng dịch vụ liên quan===
#=== (tức là phải xóa những bản gi trong bảng hop_dong) và những bản liên quan khác====
CREATE VIEW v_sp_xoa_dich_vu_va_hd_room AS
(SELECT 
            HOP_DONG.MA_HOP_DONG,
                DICH_VU.MA_DICH_VU,
                HOP_DONG.NGAY_LAM_HOP_DONG,
                DICH_VU.MA_LOAI_DICH_VU
        FROM
            HOP_DONG
        JOIN DICH_VU ON HOP_DONG.MA_DICH_VU = DICH_VU.MA_DICH_VU
        
        WHERE
            YEAR(HOP_DONG.NGAY_LAM_HOP_DONG) IN (2019 , 2020, 2021)
            AND DICH_VU.MA_LOAI_DICH_VU = 3);
DELIMITER //
CREATE PROCEDURE sp_xoa_dich_vu_va_hd_room ()
BEGIN
DELETE FROM HOP_DONG 
WHERE
    HOP_DONG.MA_HOP_DONG IN (SELECT 
        MA_HOP_DONG
    FROM (SELECT MA_HOP_DONG FROM v_sp_xoa_dich_vu_va_hd_room ) as A);

DELETE FROM DICH_VU 
WHERE
    DICH_VU.MA_DICH_VU IN (SELECT 
        MA_HOP_DONG
    FROM (SELECT MA_HOP_DONG FROM v_sp_xoa_dich_vu_va_hd_room ) as B) ;      
END//
DELIMITER ;
SET FOREIGN_KEY_CHECKS = 0; 
SET SQL_SAFE_UPDATES = 0;
CALL sp_xoa_dich_vu_va_hd_room();
SELECT * FROM HOP_DONG;
SELECT * FROM DICH_VU;